### ISSUE TITLE
Document which, if any, common gcc and clang extensions are supported

### ISSUE THREAD

**Issue by magnusjonsson** [jhjourdan/C11parser#15]
See https://gcc.gnu.org/onlinedocs/gcc/C-Extensions.html#C-Extensions

I would be particularly interested in "Statement Exprs" and "Other Builtins".

**Comment by jhjourdan** [comment]
None are supported. As said in the README file, this is a compliant ISO C parser. Nothing more, nothing less.

**Comment by magnusjonsson** [comment]
Thanks!
