### ISSUE TITLE
Unparser / prettyprinter

### ISSUE THREAD

**Issue by SamuelMarks** [jhjourdan/C11parser#21]
Is this in the works? :)

**Comment by jhjourdan** [comment]
We do not plan anything like this in the near future.

Note, however, that I don't expect this to be very difficult. The main problem with the C grammar is the lexer hack, but there should not be any probelm with the lexer hack when pretty-printing.

CompCert has a pretty-printer for one of its most high-level language, Clight, perhaps this may match your needs.
