### ISSUE TITLE
Incorrect lexing of character literals

### ISSUE THREAD

**Issue by JoJoDeveloping** [jhjourdan/C11parser#22]
According to 6.4.4.4, we have

_character-constant_:
​  ​  ​  `'` _c-char-sequence_ `'`
  
_c-char-sequence_:
​  ​  ​  _c-char_
​  ​  ​  _c-char-sequence c-char_

However, the lexer currently accepts `''` as an empty char constant.

**Comment by jhjourdan** [comment]
Thanks, you're right.

Fixed in 545e2df.
