### ISSUE TITLE
Newline in whitespace_char_no_newline ?

### ISSUE THREAD

**Issue by mingodad** [jhjourdan/C11parser#23]
It seems that although you have named it `whitespace_char_no_newline` here https://github.com/jhjourdan/C11parser/blob/a8977f2a9e0e3e714e561f3fa6c62eee220a9609/lexer.mll#L60 in reality you are including the `\n` as `\012`.

**Comment by mingodad** [comment]
I just added a partially working adaptation of this project grammar to https://mingodad.github.io/parsertl-playground/playground/ , select "C18 parser (partially working)" from the examples.

**Comment by fpottier** [comment]
As far as can tell, `\012` is not newline, it is the form feed character. I don't know what the C standard says about it, though.

**Comment by mingodad** [comment]
So probably my interpreting the `\012`  as an octal number is wrong ?

**Comment by fpottier** [comment]
I don't think it is octal. In the OCaml toplevel, `Char.code '\012'` returns `12`. I think `ocamllex` has the same conventions as OCaml.

**Comment by mingodad** [comment]
My bad !
You are right and I'm wrong.
Sorry by the trouble.

**Comment by waldyrious** [comment]
I don't know anything about OCaml, but Wikipedia [says](https://en.wikipedia.org/wiki/Page_break#Form_feed) that:

> In the C programming language (and other languages derived from C), the form feed character is represented as `'\f'`.

Could that be used here as well?

**Comment by waldyrious** [comment]
Ah, it seems like `\f` [isn't supported by OCaml](https://v2.ocaml.org/manual/lex.html#sss:character-literals). That said, in the [docs for the `String` module's `trim`](https://v2.ocaml.org/api/String.html#VALtrim) it is represented as `'\x0C'`. Perhaps that representation would be less ambiguous than `\012`?
