### ISSUE TITLE
tests have a minor failure

### ISSUE THREAD

**Issue by pmetzger** [jhjourdan/C11parser#3]
1. I note that the README should probably mention that one needs `cram` to run the tests.
2. `make test` results in this minor failure:

```
ocamlbuild -menhir "menhir --no-stdlib --unused-token IMAGINARY -lg 1 -la 1 -v" main.native
mv main.native parse
cram tests/tests.t
!
--- tests/tests.t
+++ tests/tests.t.err
@@ -30,7 +30,7 @@
   $ $PARSECMD < $TESTDIR/dangling_else.c
 SHOULD FAIL:
   $ $PARSECMD < $TESTDIR/dangling_else_misleading.fail.c
-  Fatal error: exception Parser.Basics.Error
+  Fatal error: exception Parser.MenhirBasics.Error
   [2]
   $ $PARSECMD < $TESTDIR/dangling_else_lookahead.c
   $ $PARSECMD < $TESTDIR/dangling_else_lookahead.if.c

# Ran 1 tests, 0 skipped, 1 failed.
```

**Comment by pmetzger** [comment]
See pull request #4 (presuming that just replacing the expected string is correct.)

**Comment by jhjourdan** [comment]
> I note that the README should probably mention that one needs cram to run the tests.

Fixed.

> See pull request #4 (presuming that just replacing the expected string is correct.)

Merged. The corresponding Menhir module changed its name.
