### ISSUE TITLE
Someone should check conformance with C18 draft n2176

### ISSUE THREAD

**Issue by pmetzger** [jhjourdan/C11parser#9]
C18 is out, and it's only a set of technical corrections to C11 with no substantive changes. The final draft document, N2176, is located at:
http://www.open-std.org/jtc1/sc22/wg14/www/abq/c17_updated_proposed_fdis.pdf

Someone should, at some point, check that there are no changes that would substantively alter the parser.

**Comment by pmetzger** [comment]
I have been reading through the technical defect reports. So far, I believe only the following change involves grammar changes to clarify behavior:

http://www.open-std.org/jtc1/sc22/wg14/www/docs/n2244.htm#dr_444

I believe that adding the single grammar rule in question does not break any existing C11 code, and would make the parser also conform to C18. I will have to check the document a bit more to be sure, and it would be good if someone double-checked my work.

**Comment by jhjourdan** [comment]
Thanks, done in 4b155e9c

**Comment by pmetzger** [comment]
It's still a correct parser for C11, its just also now a correct parser for C18. :)

**Comment by jhjourdan** [comment]
Alright, I added a test.
